require "rails_helper"

RSpec.describe Label, :type => :model do
  it "should parse json list payload" do
    payload = '{"total_entries":11,"page":1,"_links":{"self":{"href":"/api/v2/labels?page=1&per_page=50","class":"page"},"first":{"href":"/api/v2/labels?page=1&per_page=50","class":"page"},"last":{"href":"/api/v2/labels?page=1&per_page=50","class":"page"},"previous":null,"next":null},"_embedded":{"entries":[{"id":1938573,"name":"Abandoned Chats","description":"Abandoned Chats","enabled":true,"types":["case","macro"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938573","class":"label"}}},{"id":1944759,"name":"Brand New Label","description":"its new","enabled":true,"types":["case","macro"],"color":"brown","_links":{"self":{"href":"/api/v2/labels/1944759","class":"label"}}},{"id":1938572,"name":"Escalated","description":"Escalated","enabled":true,"types":["case","macro"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938572","class":"label"}}},{"id":1938569,"name":"Example","description":"Example","enabled":true,"types":["case"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938569","class":"label"}}},{"id":1938567,"name":"Feedback","description":"Feedback","enabled":true,"types":["case","macro"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938567","class":"label"}}},{"id":1938568,"name":"More Info","description":"More Info","enabled":true,"types":["case","macro"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938568","class":"label"}}},{"id":1938571,"name":"Negative Feedback","description":"Negative Feedback","enabled":true,"types":["case","macro"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938571","class":"label"}}},{"id":1938570,"name":"Sample Case","description":"Sample Case","enabled":true,"types":["case"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938570","class":"label"}}},{"id":1938566,"name":"Sample Macros","description":"Sample Macros","enabled":true,"types":["macro"],"color":"default","_links":{"self":{"href":"/api/v2/labels/1938566","class":"label"}}},{"id":1944704,"name":"SuperLabel","description":"Its Super!","enabled":true,"types":["case","macro"],"color":"red","_links":{"self":{"href":"/api/v2/labels/1944704","class":"label"}}},{"id":1944707,"name":"This Is Awesome","description":"Awesome","enabled":true,"types":["case","macro"],"color":"yellow","_links":{"self":{"href":"/api/v2/labels/1944707","class":"label"}}}]}}'

    result = Label.parse_json(payload)
    expect(result.class).to eq(Array)
    expect(result.size).to eq(11)
    expect(result.first.class).to eq(Label)
  end
end